<?php

namespace ContainerV0ySHqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DatabaseHandler' shared autowired service.
     *
     * @return \App\Service\DatabaseHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/DatabaseHandler.php';

        return $container->privates['App\\Service\\DatabaseHandler'] = new \App\Service\DatabaseHandler(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')));
    }
}
