<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container38e4uoc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container38e4uoc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container38e4uoc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container38e4uoc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container38e4uoc\App_KernelDevDebugContainer([
    'container.build_hash' => '38e4uoc',
    'container.build_id' => '1613070a',
    'container.build_time' => 1790872114,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container38e4uoc');
