<?php

namespace ContainerToYXVCK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx03ControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\ex03Controller' shared autowired service.
     *
     * @return \App\Controller\ex03Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ex03Controller'] = $instance = new \App\Controller\ex03Controller();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'router' => ['services', 'router', 'getRouterService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'router' => '?',
            'request_stack' => '?',
            'http_kernel' => '?',
            'twig' => '?',
            'form.factory' => '?',
            'parameter_bag' => '?',
        ]))->withContext('App\\Controller\\ex03Controller', $container));

        return $instance;
    }
}
