<?php

namespace ContainerToYXVCK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserModelRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\userModelRepository' shared autowired service.
     *
     * @return \App\Repository\userModelRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\userModelRepository'] = new \App\Repository\userModelRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
