<?php

namespace ContainerToYXVCK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidatorService extends App_KernelDevContainer
{
    /*
     * Gets the private 'validator' shared service.
     *
     * @return \Symfony\Component\Validator\Validator\ValidatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['validator.builder'] ?? $container->load('getValidator_BuilderService'));

        if (isset($container->privates['validator'])) {
            return $container->privates['validator'];
        }

        $instance = $a->getValidator();

        if (isset($container->privates['validator'])) {
            return $container->privates['validator'];
        }

        return $container->privates['validator'] = $instance;
    }
}
