<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZ7PHPN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZ7PHPN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZ7PHPN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZ7PHPN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZ7PHPN\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZ7PHPN',
    'container.build_id' => '9bdbd415',
    'container.build_time' => 1790944032,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZ7PHPN');
