<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtb7xXs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtb7xXs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAtb7xXs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAtb7xXs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAtb7xXs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Atb7xXs',
    'container.build_id' => 'c0067b33',
    'container.build_time' => 1784468753,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtb7xXs');
