<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxDkHxh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxDkHxh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxDkHxh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxDkHxh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBxDkHxh\App_KernelDevDebugContainer([
    'container.build_hash' => 'BxDkHxh',
    'container.build_id' => '5a2cbadc',
    'container.build_time' => 1784198163,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxDkHxh');
