<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerToYXVCK\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerToYXVCK/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerToYXVCK.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerToYXVCK\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerToYXVCK\App_KernelDevContainer([
    'container.build_hash' => 'ToYXVCK',
    'container.build_id' => '660a8739',
    'container.build_time' => 1790945492,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerToYXVCK');
