<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUqAKxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUqAKxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEUqAKxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEUqAKxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEUqAKxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'EUqAKxC',
    'container.build_id' => 'a37156ac',
    'container.build_time' => 1784209142,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUqAKxC');
