<?php

namespace ContainerAtb7xXs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ex03Controller::newTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::newTable()', 'getEx03ControllernewTableService', true],
            'App\\Controller\\ex03Controller::deleteTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::deleteTable()', 'getEx03ControllerdeleteTableService', true],
            'App\\Controller\\ex03Controller::listTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::listTable()', 'getEx03ControllerlistTableService', true],
            'App\\Controller\\ex03Controller::updateTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::updateTable()', 'getEx03ControllerupdateTableService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ex03Controller:newTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::newTable()', 'getEx03ControllernewTableService', true],
            'App\\Controller\\ex03Controller:deleteTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::deleteTable()', 'getEx03ControllerdeleteTableService', true],
            'App\\Controller\\ex03Controller:listTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::listTable()', 'getEx03ControllerlistTableService', true],
            'App\\Controller\\ex03Controller:updateTable' => ['privates', '.service_locator.N26aNU..App\\Controller\\ex03Controller::updateTable()', 'getEx03ControllerupdateTableService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ex03Controller::newTable' => '?',
            'App\\Controller\\ex03Controller::deleteTable' => '?',
            'App\\Controller\\ex03Controller::listTable' => '?',
            'App\\Controller\\ex03Controller::updateTable' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ex03Controller:newTable' => '?',
            'App\\Controller\\ex03Controller:deleteTable' => '?',
            'App\\Controller\\ex03Controller:listTable' => '?',
            'App\\Controller\\ex03Controller:updateTable' => '?',
        ]));
    }
}
