<?php

namespace ContainerAtb7xXs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx03ControllerdeleteTableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N26aNU..App\Controller\ex03Controller::deleteTable()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N26aNU..App\\Controller\\ex03Controller::deleteTable()'] = ($container->privates['.service_locator.N26aNU.'] ?? $container->load('get_ServiceLocator_N26aNU_Service'))->withContext('App\\Controller\\ex03Controller::deleteTable()', $container);
    }
}
