<?php

namespace ContainerAtb7xXs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\userForm' shared autowired service.
     *
     * @return \App\Form\userForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/userForm.php';

        return $container->privates['App\\Form\\userForm'] = new \App\Form\userForm();
    }
}
