<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9ioOiIH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9ioOiIH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9ioOiIH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9ioOiIH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9ioOiIH\App_KernelDevDebugContainer([
    'container.build_hash' => '9ioOiIH',
    'container.build_id' => 'e3fbda4b',
    'container.build_time' => 1783951462,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9ioOiIH');
