<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLOI2YHk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLOI2YHk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLOI2YHk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLOI2YHk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLOI2YHk\App_KernelDevDebugContainer([
    'container.build_hash' => 'LOI2YHk',
    'container.build_id' => '56a5c039',
    'container.build_time' => 1790944008,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLOI2YHk');
