<?php

namespace ContainerXZ7PHPN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx01ControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N26aNU..App\Controller\ex01Controller::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N26aNU..App\\Controller\\ex01Controller::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dbHandler' => ['privates', 'App\\Service\\databaseHandler', 'getDatabaseHandlerService', true],
        ], [
            'dbHandler' => 'App\\Service\\databaseHandler',
        ]))->withContext('App\\Controller\\ex01Controller::index()', $container);
    }
}
