<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV0ySHqx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV0ySHqx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV0ySHqx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV0ySHqx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV0ySHqx\App_KernelDevDebugContainer([
    'container.build_hash' => 'V0ySHqx',
    'container.build_id' => 'c7a39a13',
    'container.build_time' => 1790872114,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV0ySHqx');
