<?php

namespace ContainerD62bX6f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N26aNU_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N26aNU.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N26aNU.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dbHandler' => ['privates', 'App\\Service\\databaseHandler', NULL, 'Cannot autowire service "App\\Service\\databaseHandler": argument "$schemaTool" of method "__construct()" references class "Doctrine\\ORM\\Tools\\SchemaTool" but no such service exists.'],
        ], [
            'dbHandler' => 'App\\Service\\databaseHandler',
        ]);
    }
}
