<?php

namespace ContainerD62bX6f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDatabaseHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\databaseHandler' shared autowired service.
     *
     * @return \App\Service\databaseHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\databaseHandler": argument "$schemaTool" of method "__construct()" references class "Doctrine\\ORM\\Tools\\SchemaTool" but no such service exists.');
    }
}
