<?php

namespace ContainerDIhw9X2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx03ControllerlistTableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0M2jooq.App\Controller\ex03Controller::listTable()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0M2jooq.App\\Controller\\ex03Controller::listTable()'] = ($container->privates['.service_locator.0M2jooq'] ?? $container->load('get_ServiceLocator_0M2jooqService'))->withContext('App\\Controller\\ex03Controller::listTable()', $container);
    }
}
