<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'ex02_newTable' => [[], ['_controller' => 'App\\Controller\\ex02Controller::tableSetUp'], [], [['text', '/ex02/new']], [], [], []],
    'ex02_updateTable' => [[], ['_controller' => 'App\\Controller\\ex02Controller::tableUpdate'], [], [['text', '/ex02/update']], [], [], []],
    'ex02_listTable' => [[], ['_controller' => 'App\\Controller\\ex02Controller::listTable'], [], [['text', '/ex02/list']], [], [], []],
    'App\Controller\ex02Controller::tableSetUp' => [[], ['_controller' => 'App\\Controller\\ex02Controller::tableSetUp'], [], [['text', '/ex02/new']], [], [], []],
    'App\Controller\ex02Controller::tableUpdate' => [[], ['_controller' => 'App\\Controller\\ex02Controller::tableUpdate'], [], [['text', '/ex02/update']], [], [], []],
    'App\Controller\ex02Controller::listTable' => [[], ['_controller' => 'App\\Controller\\ex02Controller::listTable'], [], [['text', '/ex02/list']], [], [], []],
];
