<?php

namespace ContainerLOI2YHk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx00controllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LHyHen4.App\Controller\ex00controller::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LHyHen4.App\\Controller\\ex00controller::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dbManager' => ['privates', 'App\\Service\\SqlDatabaseManager', 'getSqlDatabaseManagerService', true],
        ], [
            'dbManager' => 'App\\Service\\SqlDatabaseManager',
        ]))->withContext('App\\Controller\\ex00controller::index()', $container);
    }
}
