<?php

namespace ContainerLOI2YHk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSqlDatabaseManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SqlDatabaseManager' shared autowired service.
     *
     * @return \App\Service\SqlDatabaseManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/SqlDatabaseManager.php';

        return $container->privates['App\\Service\\SqlDatabaseManager'] = new \App\Service\SqlDatabaseManager(($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')));
    }
}
