<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKF3ZHRU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKF3ZHRU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKF3ZHRU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKF3ZHRU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKF3ZHRU\App_KernelDevDebugContainer([
    'container.build_hash' => 'KF3ZHRU',
    'container.build_id' => '0762a66a',
    'container.build_time' => 1790872114,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKF3ZHRU');
