<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBruGGdU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBruGGdU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBruGGdU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBruGGdU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBruGGdU\App_KernelDevDebugContainer([
    'container.build_hash' => 'BruGGdU',
    'container.build_id' => 'd502176d',
    'container.build_time' => 1786970983,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBruGGdU');
