<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxOxxO2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxOxxO2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxOxxO2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxOxxO2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxOxxO2\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxOxxO2',
    'container.build_id' => '6ea7bb18',
    'container.build_time' => 1790872115,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxOxxO2');
